### ISSUE TITLE
No x86_64 builds of the latest mesa-libGL and other libraries for CentOS 7

### ISSUE THREAD

**Issue by prakhunov** [negativo17/mesa#1]
When I run a yum update on CentOS7, it wants to upgrade the following packages:

 mesa-libEGL-18.0.5-3.el7
 mesa-libGL-18.0.5-3.el7

However there only appear to be i686 builds of them and no x86_64 builds.

**Comment by scaronni** [comment]
Please enable the "cr" repository. This is required to support both RHEL and CentOS everytime there is a new release (in this case 7.6) at the same time.
